import { startVerification } from '@didit-protocol/sdk-react-native';

export const diditApiKey = process.env.EXPO_PUBLIC_DIDIT_API_KEY;

/**
 * Helper to fetch a session token and start the Didit verification flow.
 * Note: In production, session tokens should typically be generated by your backend
 * to avoid exposing the API key in the client app.
 */
export async function startDiditVerification(workflowId, vendorData = {}) {
  try {
    // 1. Fetch a session token
    const response = await fetch('https://verification.didit.me/v3/session/', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${diditApiKey}`,
      },
      body: JSON.stringify({
        workflow_id: workflowId,
        vendor_data: vendorData,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Failed to create Didit session: ${response.status} ${errorText}`);
    }

    const data = await response.json();
    const sessionToken = data.session_token;

    if (!sessionToken) {
      throw new Error('No session token returned from Didit');
    }

    // 2. Start the mobile SDK verification flow
    const result = await startVerification(sessionToken);
    return result;
  } catch (error) {
    console.error('Didit Verification Error:', error);
    throw error;
  }
}
